### ISSUE TITLE
both files appear corrupted

### ISSUE THREAD

**Issue by alexge233** [cydonia999/VGGFace2-pytorch#2]
I've tried to use any of the `pkl` files you have uploaded, but they all appear corrupted.
I tried both as a model and as a weights file:

```
import torch
import torch.nn as nn

model = torch.load("resnet50_ft_weight.pkl")
print(model)
```

```
import torch
import torch.nn as nn
import torchvision.models as models

model = models.resnet50()
model.load_state_dict(torch.load("resnet50_ft_weight.pkl"))
print(model)
```

The output is:
```
RuntimeError: Invalid magic number; corrupt file?
```

**Comment by arunsubk** [comment]
Hi All,
Could someone please reply on this thread at least to confirm if the approach used above is incorrect in anyway? Or if, there indeed is a problem with the pkl file? Asking this because I too am looking for RESNET trained on VGG-FACE, and this is the only I found so far, and i too encounter the "RuntimeError: Invalid magic..." error. 

Thanks,

**Comment by xmq1221** [comment]
I met the same error.Are those pkl files really corrupted or I load it the wrong way?

`model_scratch = 'models/resnet50_scratch_weight.pkl'
params = torch.load(model_scratch)
print(params.keys())`

error

`Traceback (most recent call last):
  File "/home/disk3/xmq/data/code/pytorch/resnet_modify/models/VGGFace2-pytorch/test_params.py", line 7, in <module>
    params = torch.load(model_scratch)
  File "/home/disk3/xmq/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/disk3/xmq/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 534, in _load
    raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file?`

**Comment by arunsubk** [comment]
@xmq1221  If you're however just looking for RESNET50 trained on VGGFACE2 the official site has a pretrained model that work fine. Pasting below the link, and also the key instruction that helps load the model:


Link: https://github.com/ox-vgg/vgg_face2 

The following instruction on this page helped:
-------------
PyTorch: Imported from Caffe models using the tool [5]. Models can be loaded by using:
import imp
import torch
# 'senet50_256_pytorch' is the model name
MainModel = imp.load_source('MainModel', 'senet50_256_pytorch.py') 
model = torch.load('senet50_256_pytorch.pth')
-------------------------------------

Thanks,
Arun

**Comment by xmq1221** [comment]
> @xmq1221 If you're however just looking for RESNET50 trained on VGGFACE2 the official site has a pretrained model that work fine. Pasting below the link, and also the key instruction that helps load the model:
> 
> Link: https://github.com/ox-vgg/vgg_face2
> 
> ## The following instruction on this page helped:
> PyTorch: Imported from Caffe models using the tool [5]. Models can be loaded by using:
> import imp
> import torch
> 
> # 'senet50_256_pytorch' is the model name
> ## MainModel = imp.load_source('MainModel', 'senet50_256_pytorch.py')
> model = torch.load('senet50_256_pytorch.pth')
> Thanks,
> Arun

I am trying to look for a model trained on VGGFACE2 which used PyTorch. I will try it! Thanks!

**Comment by schudov** [comment]
try this:

import pickle
with open('senet50_ft_weight.pkl', 'rb') as f:
  obj = f.read()
weights = pickle.loads(obj, encoding='latin1')

**Comment by RunOrVeith** [comment]
This works:

```python
def resnet50(weights_path=None, **kwargs):
    """Constructs a ResNet-50 model.
    """
    model = ResNet(Bottleneck, [3, 4, 6, 3], **kwargs)
    if weights_path:
        import pickle
        with open(weights_path, 'rb') as f:
            obj = f.read()
        weights = {key: torch.from_numpy(arr) for key, arr in pickle.loads(obj, encoding='latin1').items()}
        model.load_state_dict(weights)
    return model

model = resnet50("/path/to/weights.pkl", num_classes=8631)  # Pretrained weights fc layer has 8631 outputs
```

**Comment by ChangYuance** [comment]
import torch
import torch.nn as nn
import resnet as ResNet
model = ResNet.resnet50(num_classes=8631, include_top=False)
resume = '/home/chang_yuance/data/changyuance/codes/VGGFace2-pytorch/path/resnet50_ft_weight.pkl'
import pickle
with open(resume, 'rb') as f:
    obj = f.read()
weights = {key: torch.from_numpy(arr) for key, arr in pickle.loads(obj, encoding='latin1').items()}
model.load_state_dict(weights)
print(model)
this work for me
